### ISSUE TITLE
How to use custom checkstyle config

### ISSUE THREAD

**Issue by nitinsh99** [nikitasavinov/checkstyle-action#10]
Hi.. I have my custom config under following path: 
`support/checkstyle/checkstyle.xml`

I am trying following config but it is failing..

```
on: pull_request

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-check'
        tool_name: 'testtool'
        checkstyle_config: 'support/checkstyle/checkstyle.xml'

```

**Comment by NKcqx** [comment]
But it's already `nikitasavinov/checkstyle-action@master`

**Comment by nitinsetter99** [comment]
> But it's already `nikitasavinov/checkstyle-action@master`

@NKcqx  so there is no way to use any other check style config other than google_checks.xml?

**Comment by NKcqx** [comment]
> > But it's already `nikitasavinov/checkstyle-action@master`
> 
> @NKcqx so there is no way to use any other check style config other than google_checks.xml?

I don't know, trynna figure it out too.
Here's mine, I got the `checkstyle.xml` under project's root path:
```
- name: Checkout
        uses: actions/checkout@v2
      - name: Run java checkstyle
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'testtool'
          checkstyle_config: 'checkstyle.xml'
```
And got the result (already ran checkStyle locally without error):
![image](https://user-images.githubusercontent.com/26196566/87229687-d4e1a300-c3dc-11ea-98b8-775af0fa744c.png)
