### ISSUE TITLE
The Pipeline does not fail with 'fail_on_error: true'

### ISSUE THREAD

**Issue by SimonHarmonicMinor** [nikitasavinov/checkstyle-action#24]
I added yml configuration according to the guideline.
```yml
name: "Run Java Checkstyle"

on: pull_request

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          checkstyle_config: 'codestyle/checkstyle.xml'
          checkstyle_version: '8.42'
          fail_on_error: true
```
Even that `fail_on_error` is set to `true`, the checkstyle pipeline finishes successfully.
Here is the link to PR: SimonHarmonicMinor/Java-Useful-Utils#72
