### ISSUE TITLE
Correction in readme

### ISSUE THREAD

**Issue by james-s-w-clark** [nikitasavinov/checkstyle-action#34]
https://github.com/nikitasavinov/checkstyle-action#checkstyle_config

```
checkstyle_config
Required......
```

It's not in the example usage - so either the example usage is broken, or it's not a required field.
I'm not sure what the preference is, so I'm raising an issue rather than a PR :)

```
on: pull_request

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-check'
        tool_name: 'testtool'
```
